import { Patient, WaitingListApiRequest } from "./models"

export const mockPatientData: Patient = {
  id: 1,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deletedAt: new Date().toISOString(),
  riskScore: {
    InclusionLabel: "",
    InclusionLabelType: "",
    TriageScore: "",
  },
}

export const mockWaitingListApiRequest: WaitingListApiRequest = {
  cdPersonID: "1145859122234",
  cdPersonForeignID: "",
  cdPersonPassportID: "",
  cdPersonNationalityCode: 70,
  cdPersonNameTitleCode: 3,
  cdPersonFirstName: "Test",
  cdPersonMiddleName: "",
  cdPersonLastName: "Test",
  cdPersonGenderCode: 1,
  cdPersonAge: 25,
  cdPersonBirthDate: "25640728",
  cdPersonPhone1: "0976485638",
  cdPersonPhone2: "0864536253",
  cdPersonCustodialPhone1: "0675647460",
  cdPersonCustodialPhone2: "0876453672",
  cdPersonWeightMeasure: 80,
  cdPersonHeightMeasure: 172,
  cdPersonBMIMeasure: 85.74,
  emLaboratoryTestATK: true,
  emLaboratoryTestRTPCR: true,
  emLaboratoryTestDate: "2021-08-09T00:00:00.000+07:00",
  emPatientGotFavipiravir: true,
  emPatientGotFavipiravirDate: "2021-06-01",
  emPatientCommitTemperature: 39,
  emPatientCommitPulse: 47,
  emPatientCommitOxygenSaturation: 86,
  emPatientCommitOxygenSaturationPost: 78,
  emPatientCommitOxygenSaturationDiff: 49,
  emPatientCommitSystolic: 120,
  emPatientCommitDiastolic: 50,
  emPatientCommitInspirationRate: 90,
  emPatientPregnancyStatus: false,
  emPatientPregnancyWeeks: undefined,
  emPatientBedriddenStatus: false,
  emPatientSymptomsText: "อาการทั่วไปล่าสุด",
  emPatientAllergyDrug: "การแพ้ยา",
  emPatientAllergyFood: "การแพ้อาหาร",
  emPatientFoodText: "การบริโภคอาหารเฉพาะ",
  emPatientSymptomsCL1: true,
  emPatientSymptomsCL2: true,
  emPatientSymptomsCL3: true,
  emPatientSymptomsCL4: true,
  emPatientSymptomsCL5: true,
  emPatientSymptomsCL6: true,
  emPatientSymptomsCL7: true,
  emPatientSymptomsCL8: true,
  emPatientSymptomsCL9: true,
  emPatientSymptomsCL10: false,
  emPatientSymptomsCL11: false,
  emPatientSymptomsCL12: false,
  emPatientSymptomsCL13: false,
  emPatientSymptomsCL14: false,
  emPatientDiseaseCD1: false,
  emPatientDiseaseCD2: false,
  emPatientDiseaseCD3: false,
  emPatientDiseaseCD4: false,
  emPatientDiseaseCD5: false,
  emPatientDiseaseCD6: false,
  emPatientDiseaseCD7: false,
  emPatientDiseaseCD8: false,
  emPatientDiseaseCD9: false,
  emPatientDiseaseCD10: false,
  emPatientDiseaseCD11: false,
  emPatientDiseaseCD12: false,
  emPatientDiseaseCD13: false,
  emHICICode: 1,
  emHICITypeCode: 2,
  cdMedicalDoctorCode: "dt1284",
  emPatientCheckInDate: "2021-06-01T00:00:00.000+07:00",
  emPatientCheckOutDate: "2021-06-01T00:00:00.000+07:00",
  crProvinceCode: "10",
  crAmpurCode: "1010",
  crTumbolCode: "100101",
  crMooCode: "11010201",
  crRoad: "ชื่อถนน",
  crTrok: "ชื่อตรอก",
  crSoi: "ชื่อซอย",
  crVillage: "ชื่อหมู่บ้าน",
  crZoneCode: 1,
  crBuildingName: "ชื่อตึก",
  crAddressText: "รายละเอียดเพิ่มเติม",
  crGeographicCoordinateLatitude: "18.767524",
  crGeographicCoordinateLongitude: "98.930124",
  emPatientCommitDate: "2021-06-01T00:00:00.000+07:00",
  emPatientMovementDate: "2021-06-01T00:00:00.000+07:00",
  emPatientWaitingHours: 48,
  emSourceNumberCode: 13,
  emMoveToLocationCode: "Horganice",
  emMoveToLocationTypeCode: "8",
  emMoveFromLocationCode: "บ้าน",
  emMoveFromLocationTypeCode: "12",
  emMoveToMethodCode: "2",
  cdOrganizationMedicalUnit: 35339,
  hsPatientHospitalNumber: "เลขที่ผู้ป่วยนอก (HN)",
  hsPatientAdmissionNumber: "เลขที่ผู้ป่วยใน (AN)",
  hsPatientHealthCoverage: 3,
  riskScore: {
    InclusionLabel: "",
    InclusionLabelType: "",
    TriageScore: "",
  },
}
